version: '3.3'

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    restart: always
    ports:
      - '9000:9000' # web-ui (http)
      # - "443:9000"  # web-ui (https)
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ulimits:
      nofile:
       soft: 65536
       hard: 65536
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs to have explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

reverse_proxy:
    container_name: reverse_proxy
    depends_on:
      - sonarqube
    image: nginx
    networks:
      - sonarnet
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /data/docker-volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /data/docker-volumes/nginx/sonarqube.crt:/etc/ssl/certs/sonarqube.crt
      - /data/docker-volumes/nginx/sonarqube.key:/etc/ssl/private/sonarqube.key

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
